apiVersion: v1
kind: Secret
metadata:
  name: viktor-expensy-secret
  namespace: viktor-expensy
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: change-me
  MONGO_INITDB_ROOT_PASSWORD: change-me
  REDIS_PASSWORD: change-me
